FROM registry.caffeina.co/devops/nador-images/nginx-base/master/nginx:latest

COPY ./backend_magento/nginx/config/sites-enabled/magento.conf /etc/nginx/sites-enabled/
COPY ./backend_magento/nginx/config/nginx.conf /etc/nginx/

