#!/bin/sh
set -ex

## This can't be done with user www-data and is obsolete regardless
## For production, app must be copied to /init
if [ ! -z "$(ls -A /. | grep init)" -a "$ENVIRONMENT" != "development" ]; then
	if [ ! -z "$(ls -A $WORKDIR/)" ]; then
		rm -f $WORKDIR/*
	fi

	mv /init/* $WORKDIR/
	rm -rf /init
fi

docker-php-entrypoint "$@"
