#!/bin/sh
set -ex

## If we are in development and workdir is not empty
## don't overwrite it with plain magento code from init
## thus delete init
if [ "$ENVIRONMENT" == "development" -a $(ls -A $WORKDIR | wc -l) -gt 1 ];
then
  if [ ! -z "$(ls -A /. | grep init)" -a $(ls -A /init | wc -l) -gt 1 ];
  then
    rm -rf $(ls -A /init)
  fi
fi

## If init is not empty, then we are in Production and should
## update our source code in workdir
if [ ! -z "$(ls -A /. | grep init)" -a $(ls -A /init | wc -l) -gt 1 ];
then
  cd /init
  mv $(ls -A /init) $WORKDIR
  rm -rf $(ls -A /init)
  cd $WORKDIR
fi

## Composer generate autoload files
## These ones needs auth.json
# composer u --no-cache
composer -o dump-autoload # doesn't need auth

## Magento install config
php $WORKDIR/bin/magento \
  setup:install \
  --base-url=${VIRTUAL_PROTO}://${VIRTUAL_HOST}/magento2ee \
  --db-host=${MYSQL_HOST} \
  --db-name=${MYSQL_DATABASE} \
  --db-user=${MYSQL_USER} \
  --db-password=${MYSQL_PASSWORD} \
  --backend-frontname=${BACKEND_FRONTNAME} \
  --admin-firstname=${ADMIN_FIRSTNAME} \
  --admin-lastname=${ADMIN_LASTNAME} \
  --admin-email=${ADMIN_EMAIL} \
  --admin-user=${ADMIN_USERNAME} \
  --admin-password=${ADMIN_PASSWORD} \
  --language=${LANGUAGE} \
  --currency=${CURRENCY} \
  --timezone=${TIMEZONE} \
  --use-rewrites=${REWRITES_ENABLED}

## Magento redis enable as session manager
php $WORKDIR/bin/magento \
  setup:config:set
  --session-save=redis \
  --session-save-redis-host=${REDIS_HOST} \
  --session-save-redis-log-level=3 \
  --session-save-redis-db=2

## Magento redis as default caching
php $WORKDIR/bin/magento \
  setup:config:set \
  --cache-backend=redis \
  --cache-backend-redis-server=${REDIS_HOST} \
  --cache-backend-redis-db=0

## Magento redis full page cache
php $WORKDIR/bin/magento \
  setup:config:set \
  --page-cache=redis \
  --page-cache-redis-server=${REDIS_HOST} \
  --page-cache-redis-db=1

## Enabling Varnish
php $WORKDIR/bin/magento \
  setup:config:set \
  --http-cache-hosts=${VARNISH_HOST}

php $WORKDIR/bin/magento \
  config:set \
  --scope=default \
  --scope-code=0 \
  system/full_page_cache/caching_application 2

## Setting Magento mode
php $WORKDIR/bin/magento \
  deploy:mode:set \
  ${MAGENTO_MODE}

exit 0
