#!/bin/sh
set -ex

if [ ! -z "$(ls -A /. | grep init)" ]; then

  if [ "$(ls -A /init | wc -l)" -gt 0 ]; then
    echo "Removing unused code"
    rm -rf /init
  fi

fi

## Installing Magento cronjob
php $WORKDIR/bin/magento cron:install --force

docker-php-entrypoint "$@"
